Repository AICoE/s2i-custom-notebook, pull requests merged in 2020-06, with the labels that each got.

#9 Add an example ImageStream template
  README.md
  openshift/oc-imagestream.yaml
Labels: approved, size/M

#12 Generate README only when var `GIT_REPO_URL` is set
  s2i/bin/run
Labels: approved, size/S

#15 include all the information into the image
  s2i/bin/assemble
  s2i/bin/run
Labels: approved, size/XS

#22 Add version.py
  version.py
Labels: approved, size/S

#24 Release of version 0.2.0
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#21 Update custom image to datahub doc
  aicoe/add-image-to-datahub.md
Labels: approved, size/S
